### ISSUE TITLE
upgrade parallelproj requirement to 1.2

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#1033]
CMake doesn't use v1.0 as we currently require 0.8.

@gschramm says

> Since there are only TOF-related changes between 0.8 and 1.0
https://github.com/gschramm/parallelproj/releases/tag/v1.0.0
it should be safe to require to v1.0.

**Comment by KrisThielemans** [comment]
It would be best to enable some of our tests with parallelproj first or even in the same PR. Note that when upgrading we'll need to change
https://github.com/UCL/STIR/blob/f979fe3fa409f9b66079443156e40f8c7ddc1af3/.github/workflows/build-test.yml#L136

**Comment by gschramm** [comment]
@Kris: The changes required on the STIR side to go from v0.8 to v1.x should be small.
The only thing that has changed in the API is that all TOF projectors now take two additional arguments that
indicate whether the TOF resolution and the TOF center offset are LOR-dependent or not (a good thing requested by you a while ago). For the non-TOF projectors no changes are needed

https://github.com/gschramm/parallelproj/blob/bb344d5a92896a15b06c562ac10d38b913d1b58f/cuda/include/parallelproj_cuda.h#L154

I won't have time to submit / test a proper PR in the next weeks, but in the end it all that is needed is adding two "0"s to the call of the TOF projectors (I guess you don't use LOR-dependent TOF properties yet).

**Comment by KrisThielemans** [comment]
that's great. @markus-jehl is checking that parallelproj tests, so hopefully we can put those in as well as upgrade. (I'm a bit reluctant to upgrade without any testing whatsoever)

**Comment by gschramm** [comment]
+1 for more (automated) testing ;)
(1) In parallelproj, I was not testing "princinple direction 0" which is why I never saw the bug :/
(2) Can you think of a good test that we can run for TOF projectors? For "simple" non-TOF projectors it is quite easy to verify what the "correct (analytical)" result should be, but for TOF projectors with a (non trivial) TOF kernel that seems way harder to me. Of course, I could use the current behavior as "gold standard", but I would prefer a "real" test.

**Comment by KrisThielemans** [comment]
we have some automated tests for projectors based on geometry etc. @danieldeidda added a few last year to be able to test blocksoncylindrical. We also have some tests using GATE data, see #991

For TOF (still in PR stage #304), we have a test with a GATE sim with very high TOF resolution https://github.com/NikEfth/STIR/pull/30, which essentially backprojects and checks if the MLP is close to the point source

**Comment by gschramm** [comment]
But do those tests also tests wheter e.g the TOF kernel is evaluated correctly? E.g. if I make a mistake in the TOF kernel implementation (kernel is a bit wider or narrower that it should be), is that being detected? I guess the MLP is not affected in that case.

**Comment by KrisThielemans** [comment]
that's correct. I'm not 100% sure if we have a test on the TOF kernel. Maybe @NikEfth recalls. Or we could check the code...

**Comment by NikEfth** [comment]
Hi, before I hand over the PR to others, I had such a test. But it involved exporting the LORs with applied TOF kernels as text files, opening them in Matlab, and doing some fittings. 
I tried to automate it with the utility to evaluate spatial resolution (but applied on an "image" filled with the values of the LOR), and it was almost ready at some point. If it is of interest, I  can look it up. It is in a branch somewhere.

**Comment by NikEfth** [comment]
@gschramm 

> 2) Can you think of a good test that we can run for TOF projectors? 
For me the best test is to add all the TOF LORs and compare it with the nonTOF LOR. Ideally, they should be identical.

**Comment by gschramm** [comment]
> @gschramm
> 
> > 2. Can you think of a good test that we can run for TOF projectors?
> 
> For me the best test is to add all the TOF LORs and compare it with the nonTOF LOR. Ideally, they should be identical.

But is that really testing whether you have implemented the TOF kernel you want to use in a correct way?
E.g. if you, by mistake, instead of using the correct TOF kernel, use a kernel that is 1/number_of_tof_bins, the sum of the TOF LOR backprojections will also be equal to the non-TOF LOR backprojection.

I was more thinking of a test of forward projecting a point or backprojecting a single TOF bin and compare the result against sth we can predict analytically. 
I guess we could say, if we know that the non-TOF back projections are correct, the TOF back projection, should be equal to the non-TOF backprojection times the TOF kernel.
But not sure if we can come up with a robust test for that.

**Comment by NikEfth** [comment]
> But is that really testing whether you have implemented the TOF kernel you want to use in a correct way?
> E.g. if you, by mistake, instead of using the correct TOF kernel, use a kernel that is 1/number_of_tof_bins, the sum of the TOF LOR backprojections will also be equal to the non-TOF LOR backprojection.

The correct kernel is something that I understand less and less every time I read about TOF. 
If you mean that the kernel you generate has the expected sd, why should it not? If you mean whether it represents the data ..., I don't believe it is possible to know. We accept that an average TOF kernel is suitable for most data. It should not be too large or too small. Although, **slighlty** larger offers better contrast.  

> I was more thinking of a test of forward projecting a point or backprojecting a single TOF bin and compare the result against sth we can predict analytically.

I am not sure what question you would like this test to answer. Is it, maybe, whether the Siddon+TOF worked? 

> I guess we could say, if we know that the non-TOF back projections are correct, the TOF back projection, should be equal to the non-TOF backprojection times the TOF kernel.

To me, this looks very similar to the proposal in the previous post. Or is it different? 
Please see Figure 2, [here](https://www.researchgate.net/publication/329789570_Implementation_and_validation_of_time-of-flight_PET_image_reconstruction_module_for_listmode_and_sinogram_projection_data_in_the_STIR_library)

**Comment by gschramm** [comment]
I was indeed referring to a test that tests whether e.g. the implemented standard deviation (or shape) of the TOF kernel is correct. For a Gaussian convolved with rectangular TOF bin, this is indeed not too hard to implement, but you there is always a chance of messing up units, factors of 2 ...
And if we go to non-Gaussian kernels, I guess it would be nice to test whether the shape of the kernel that gets applied is really what we want.

**Comment by NikEfth** [comment]
OK, now I understand. 
I suggest, then, calculating a kernel (with python) and storing it in a file. The points of the kernel should be closer than the voxel size of the density in the test. 
Export the weights of a single TOF-LOR and alight the peaks with the stored. 
Then get a metric as chi-square. Because the number of points will depend on the relationship between the voxel size and kernel size, a good score might be tricky. It will depend on view, segment etc etc
