### ISSUE TITLE
chained normalisation unstable with openmp

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [UCL/STIR#150]
When STIR is built with openmp, SIRF demos involving chained normalisation become unstable: sometimes they work and some other times either crash (mostly Matlab) or produce wrong results. No such behavior has been observed without openmp.

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov could you please clarify under which circumstances this occurs? we had a bug in `BinNormalisationFromProjData` but I thought I had fixed that.

Does it only occur with the chained? Which ones are you chaining?

I see that we don't have tests for `ChainedBinNormalisation`(sorry). Nevertheless, I'd be somewhat surprised if that's where the problem is, so instead suspect more `BinNormalisationFromECAT8`. Maybe you could check with only that enabled?

**Comment by evgueni-ovtchinnikov** [comment]
I no longer observe any abnormal behaviour when using chained normalisation  – so your bug fix must have solved the problem.

**Comment by KrisThielemans** [comment]
aha! Perfect. possibly a case of different STIR versions/branches/whatever. th
