### ISSUE TITLE
Suggestion: Allow for some tolerance in numerical prescion in computation of `x^T H x` test calculations

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#1548]
A suggestion based upon a failing test thread in stir-users email list.

This objective function concavity test was found to fail:
```
Error : 0 is larger than 0,
FAIL: PoissonLLListModeData: Computation of x^T H x = 0.000000 > 0 (Hessian) and is therefore NOT concave
 >target image max=0.999849
 >target image min=1.16359e-05
 >output image max=0
 >output image min=0
Writing diagnostic files to PoissonLLListModeData_concavity_out.hv, *target.hv
```
that comes from here:
https://github.com/UCL/STIR/blob/a008e73a36fc4dedffe4170c698c5ed18c5972a8/src/include/stir/recon_buildblock/test/ObjectiveFunctionTests.h#L228-L244

This isn't found in CI but the test might be too strict. I suggest the `x^T H x` calculation is compared to a small negative number, similar to that in `test_priors`
https://github.com/UCL/STIR/blob/a008e73a36fc4dedffe4170c698c5ed18c5972a8/src/recon_test/test_priors.cxx#L247-L268

**Comment by KrisThielemans** [comment]
This failure occurs on MacOS CI, which is therefore disabled... See #1491 for more info and some other cases where it fails.

It does appear that the test should be relaxed
https://github.com/UCL/STIR/blob/a008e73a36fc4dedffe4170c698c5ed18c5972a8/src/include/stir/recon_buildblock/test/ObjectiveFunctionTests.h#L229
tests for "strict" concavity, which is not guaranteed. I wonder if using `check_if_less_or_equal` (which actually we don't have in `RunTests`) would resolve this.

On the other hand, I'm surprised that this tests gives 0 for `x^T H x`. I had a look at the construction of `target`, which seems to be here:
https://github.com/UCL/STIR/blob/a008e73a36fc4dedffe4170c698c5ed18c5972a8/src/recon_test/test_PoissonLogLikelihoodWithLinearModelForMeanAndListModeWithProjMatrixByBin.cxx#L147-L154
I note that the writing is in the wrong place (should be after the filling), so we currently cannot check what's in there, but according to the min/max in the diagnostics, `target` is (strictly) positive. That implies that `H x` has to be non-negative, and hence `x^T H x > 0`.

In `test_priors`, we needed to allow a small negative number because `H` contains negative numbers. However, for the Poisson LL, this is not the case.

So, I don't understand what's going on, and am therefore reluctant to just let the test pass...

**Comment by robbietuk** [comment]
That makes sense. I'll close this because #1491 probably covers it.
