### ISSUE TITLE
STIR Python Interface - Segmentation fault[11] macos

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#291]
When trying to import stir in python I am getting a segmentation fault.

We have tried to use the lldb debugger with @eliseemond and we get the following error trace.

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
    frame #0: 0x000000010e166272 libpython3.7m.dylib`PyTuple_New + 322
libpython3.7m.dylib`PyTuple_New:
->  0x10e166272 <+322>: movq   0x8(%rax), %rdx
    0x10e166276 <+326>: movq   %rdx, -0x10(%r14)
    0x10e16627a <+330>: movq   %rcx, (%rdx)
    0x10e16627d <+333>: movq   %rcx, 0x8(%rax)
Target 0: (python) stopped.
```

My OS is macOS Mojave version 10.14.1, SWIG Version 3.0.12, Boost version 1.68.0, and xcode clang compiler (clang-1000.11.45.5). Using anaconda python 3.7

I get the same issue if I compile with gcc.

**Comment by eliseemond** [comment]
I have performed the same test on Windows (VS 2017), boost 1.65.1, anaconda python 3.6 and swig 3.0.12. The Python interface to STIR works fine on the platform.

**Comment by KrisThielemans** [comment]
Most likely the issue is that STIR was compiled with a certain version of Python, but when you run, the system finds another one. This is a bit of a nightmare, certainly so on Mac (you can have the system one, a few from homebrew, you have one from anaconda,etc). 

In principle, you have to activate your anaconda python version before building, and when running, and it should work. In practice, CMake isn't great in sorting this out and is known to find other versions anyway.

Some pointers on this are [in the SIRF wiki](https://github.com/CCPPETMR/SIRF/wiki/SIRF-and-Python).

Can you check what CMake found for Python (look for Python variables, probably hidden by default, so toggle "Advanced" on). The include and libraries files should be consistent. If they are not, you could attempt to make them so. Once they are, then the next step is to make sure you use that python version when running STIR. (I believe CMake should set PYTHON_EXECUTABLE). That still isn't necessarily enough but it is becoming unlikely you'd have a problem then.

Note that it isn't necessarily just the version itself, as Python can be compiled in different way, but you really need to have linked with the files from the python version that you run.

**Comment by eliseemond** [comment]
> 
> 
> Most likely the issue is that STIR was compiled with a certain version of Python, but when you run, the system finds another one. This is a bit of a nightmare, certainly so on Mac (you can have the system one, a few from homebrew, you have one from anaconda,etc).
> 
> In principle, you have to activate your anaconda python version before building, and when running, and it should work. In practice, CMake isn't great in sorting this out and is known to find other versions anyway.
> 
> Some pointers on this are [in the SIRF wiki](https://github.com/CCPPETMR/SIRF/wiki/SIRF-and-Python).
> 
> Can you check what CMake found for Python (look for Python variables, probably hidden by default, so toggle "Advanced" on). The include and libraries files should be consistent. If they are not, you could attempt to make them so. Once they are, then the next step is to make sure you use that python version when running STIR. (I believe CMake should set PYTHON_EXECUTABLE). That still isn't necessarily enough but it is becoming unlikely you'd have a problem then.
> 
> Note that it isn't necessarily just the version itself, as Python can be compiled in different way, but you really need to have linked with the files from the python version that you run.

We will try that tomorrow and close this issue if sorted. Thank you.

**Comment by robbietuk** [comment]
Fixed the issue and now I can `import stir` and have access to stir functions.

`which python` linked to `/Users/RobertTwyman/anaconda3/bin/python` which is what Cmake appeared to be finding correctly.

I believe CMake was finding an Anaconda 3.7 install on my mac. I switched the CMake settings to a python 3.6 install to success.

Thank you all with notable thanks to @eliseemond and @bathomas.
