### ISSUE TITLE
Compilation Error with Xcode and ROOT

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#315]
Error due to unique_ptr implementation in Clang, creating the following error at compilation time:

`[  8%] Building CXX object src/IO/CMakeFiles/IO.dir/InputStreamFromROOTFile.cxx.o
In file included from /Users/RobertTwyman/STIR_bin/STIR/src/IO/InputStreamFromROOTFile.cxx:20:
In file included from /Users/RobertTwyman/STIR_bin/STIR/src/include/stir/IO/InputStreamFromROOTFile.h:37:
In file included from /Users/RobertTwyman/ROOT_bin/install/include/TROOT.h:28:
In file included from /Users/RobertTwyman/ROOT_bin/install/include/TDirectory.h:24:
In file included from /Users/RobertTwyman/ROOT_bin/install/include/TBuffer.h:25:
In file included from /Users/RobertTwyman/ROOT_bin/install/include/TClass.h:31:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/unordered_set:323:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:957:13: error: too many template arguments for
      class template 'auto_ptr'
    typedef unique_ptr<__next_pointer[], __bucket_list_deleter> __bucket_list;
            ^                            ~~~~~~~~~~~~~~~~~~~~~~
/Users/RobertTwyman/STIR_bin/STIR/src/include/stir/unique_ptr.h:84:20: note: expanded from macro 'unique_ptr'
#define unique_ptr auto_ptr
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2029:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS auto_ptr
`

To fix this, unordered_set was added to the include list in unique_ptr.h .

However, a new compilation error arises:

`[ 10%] Building CXX object src/IO/CMakeFiles/IO.dir/InputStreamFromROOTFileForCylindricalPET.cxx.o
In file included from /Users/RobertTwyman/STIR_bin/STIR/src/IO/InputStreamFromROOTFile.cxx:20:
In file included from /Users/RobertTwyman/STIR_bin/STIR/src/include/stir/IO/InputStreamFromROOTFile.h:38:
In file included from /Users/RobertTwyman/ROOT_bin/install/include/TSystem.h:37:
In file included from /Users/RobertTwyman/ROOT_bin/install/include/TTimer.h:45:
In file included from /Users/RobertTwyman/ROOT_bin/install/include/TSysEvtHandler.h:25:
In file included from /Users/RobertTwyman/ROOT_bin/install/include/TQObject.h:43:
In file included from /Users/RobertTwyman/ROOT_bin/install/include/TVirtualQConnection.h:16:
/Users/RobertTwyman/ROOT_bin/install/include/TInterpreter.h:257:85: error: no viable conversion from returned value of type 'int' to function return type
      'std::auto_ptr<TInterpreterValue>'
   virtual std::unique_ptr<TInterpreterValue> MakeInterpreterValue() const { return 0; }
                                                                                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2037:31: note: candidate constructor not viable: no known
      conversion from 'int' to 'std::__1::auto_ptr<TInterpreterValue> &' for 1st argument
    _LIBCPP_INLINE_VISIBILITY auto_ptr(auto_ptr& __p) throw() : __ptr_(__p.release()) {}
                              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2065:31: note: candidate constructor not viable: no known
      conversion from 'int' to 'auto_ptr_ref<TInterpreterValue>' for 1st argument
    _LIBCPP_INLINE_VISIBILITY auto_ptr(auto_ptr_ref<_Tp> __p) throw() : __ptr_(__p.__ptr_) {}`

Adding #include <memory> to the list did not resolve this.

**Comment by KrisThielemans** [comment]
This is a failure of the work-arounds for non-compliant C++-11 compilers (discussed in #63, [code is here](https://github.com/UCL/STIR/blob/14f177a42af18187c27f17ab064050f8103aff11/src/include/stir/unique_ptr.h#L70)).

We could add `unordered_set` and `TSystem.h` to the list of files to include before `#defining` `unique_ptr` but this all feels terribly unsafe (and tricky anyway, as `unordered_set` is only available since C++-11, so we'd have to check for its existence in CMake).

We currently use Boost to check if `unique_ptr` works ([see here](https://github.com/UCL/STIR/blob/14f177a42af18187c27f17ab064050f8103aff11/src/CMakeLists.txt#L182)). It appears that Boost claims that Apple Clang is still not compliant for some reason (tested with BOOST version 1.68.0_1, Apple LLVM version 10.0.0 (clang-1000.11.45.5))

However, we checked that using `std::unique_ptr` in STIR did work (i.e. it compiles and `ctest` is ok). So probably the better solution is to check ourselves of the `std::unique_ptr` implementation is good enough. Something like this
```cmake
check_cxx_source_compiles("
   #include <memory>
   std::unique_ptr<int> f() { int *ptr = new int; return std::unique_ptr<int>(ptr); }
   int main() { auto p = f(); return 0; }
   "
   STIR_HAVE_UNIQUE_PTR)

if(STIR_HAVE_UNIQUE_PTR)
  option(STIR_NO_UNIQUE_PTR "Disable use of std::unique_ptr" OFF)
else()
   set(STIR_NO_UNIQUE_PTR ON)
endif()
```
@robbietuk want to try a PR for this?
