### ISSUE TITLE
UseITK upstream issue: ITK is added to the global include path 

### ISSUE THREAD

**Issue by rijobro** [UCL/STIR#432]
I've created an issue on ITK (https://github.com/InsightSoftwareConsortium/ITK/issues/1450) flagging up the use of `include_directories` and `link_directories` in `UseITK.cmake`. 

Can't imagine it'll be a quick fix (if at all), but we'll see what they say.

**Comment by KrisThielemans** [comment]
This can cause problems for SIRF etc or others who include STIR via CMake as the ITK include directory is therefore added to the global include path
https://github.com/UCL/STIR/blob/6417022e54a4814f25776bc8ca1df3acd4e865f6/src/cmake/STIRConfig.cmake.in#L82

Internally, we don't mind that the ITK include path added for all files (currently anyway).

However, it turns out that we don't need `include(${ITK_USE_FILE})` in STIRConfig.cmake (see #1518). While https://github.com/InsightSoftwareConsortium/ITK/issues/1450 suggests some ways to circumvent the `ITK_USE_FILE` problem, updating STIRConfig.cmake solves most problems, so I won't fix this.
