### ISSUE TITLE
List-Mode File Processing error for Siemens mMR Scanner

### ISSUE THREAD

**Issue by pw351** [UCL/STIR#62]
We are trying to work with data obtained from Siemens mMR scanner and it is in list mode format. We would like to unlist it using the same procedure we usually follow for every list-mode data. But for some list-mode files, lm_to_projdata frame definition doesn't work.
It only processes very few events for these list-mode files even though list_lm_events and coincidence flag gives a huge amount of events. The message is as below:

WARNING: KeyParser: keyword 'PET STUDY (Emission data)' already registered for parsing, overwriting previous value

WARNING: KeyParser: keyword 'PET STUDY (Image data)' already registered for parsing, overwriting previous value

WARNING: KeyParser: keyword 'PET STUDY (General)' already registered for parsing, overwriting previous value

WARNING: KeyParser: keyword 'PET data type' already registered for parsing, overwriting previous value

WARNING: KeyParser: keyword 'process status' already registered for parsing, overwriting previous value

WARNING: KeyParser: keyword 'IMAGE DATA DESCRIPTION' already registered for parsing, overwriting previous value

WARNING: KeyParser: keyword 'data offset in bytes' already registered for parsing, overwriting previous value

WARNING: Interfile error: 'number of bytes per pixel' keyword should be set
 to a number > 0

INFO: CListModeDataECAT8_32bit: opening file PET_ACQ_542_20161117184346-0.l
LmToProjData NOT Using FRAME_BASED_DT_CORR

Processing time frame 1

Number of prompts stored in this time period : 17949
Number of delayeds stored in this time period: 0

Processing time frame 2

Number of prompts stored in this time period : 1829
Number of delayeds stored in this time period: 0
Last stored event was recorded before time-tick at 36459.7 secs
Total number of counts (either prompts/trues/delayeds) stored: 19778

This took 1.46s CPU time.

We define the frame in different frame definition file as follows:
1  30
1  130

This scan is 3600 s long but the frame we defined are less time.
We also tried:
1  3600 ; as our frame definition;
the message it gives is as follows:

WARNING: KeyParser: keyword 'PET STUDY (Emission data)' already registered for parsing, overwriting previous value

WARNING: KeyParser: keyword 'PET STUDY (Image data)' already registered for parsing, overwriting previous value

WARNING: KeyParser: keyword 'PET STUDY (General)' already registered for parsing, overwriting previous value

WARNING: KeyParser: keyword 'PET data type' already registered for parsing, overwriting previous value

WARNING: KeyParser: keyword 'process status' already registered for parsing, overwriting previous value

WARNING: KeyParser: keyword 'IMAGE DATA DESCRIPTION' already registered for parsing, overwriting previous value

WARNING: KeyParser: keyword 'data offset in bytes' already registered for parsing, overwriting previous value

WARNING: Interfile error: 'number of bytes per pixel' keyword should be set
 to a number > 0

INFO: CListModeDataECAT8_32bit: opening file PET_ACQ_542_20161117184346-0.l
LmToProjData NOT Using FRAME_BASED_DT_CORR

Processing time frame 1

Number of prompts stored in this time period : 17949
Number of delayeds stored in this time period: 0
Last stored event was recorded before time-tick at 36459.7 secs
Total number of counts (either prompts/trues/delayeds) stored: 17949

This took 0.7s CPU time.

Whereas when we use all the events, then it processes everything but only with one computer whereas it doesnt work on other including HPC.
This happens for some list-mode files only, whereas others are fine!!
Very mysterious!

**Comment by KrisThielemans** [comment]
I think the underlying reason for this is that `LmToProjData` just keeps calling `get_next_record` until it fails and then stops (in the case of the mMR, this will be calling `InputFileFromStream::get_next_record()` which has stuff like
```
  stream_ptr->read(data_ptr, this->size_of_record_signature);
  if (stream_ptr->gcount()<static_cast<std::streamsize>(this->size_of_record_signature))
    return Succeeded::no; 
```
This means that as soon as there's some IO problem, `LmToProjData` will assume it's the end of the listmode file. The reason for this design is that in many listmode formats there's no way to know how many events there will be in the file. Of course, for some file formats including the one used by the mMR there is a field that says something about number of counts (but the number of records is larger than that, as it also stores timing events, singles, whatever). If anyone has any ideas to improve on this design, that'd be great.

However, I don't understand understand why you're having problems on some files or on some computers. It looks like some time-out to me. I cannot see why using the standard C++ fstream interface would fail to read all bits of a file...

I have no suggestions on how to fix this.

**Comment by NikEfth** [comment]
If it is the case of a badbit why then there is not the "Error after reading from list mode stream in get_next_record" warning?

**Comment by NikEfth** [comment]
[Desktop.zip](https://github.com/UCL/STIR/files/649743/Desktop.zip)
I just made this two simple scipts. Apparently I have more free time than I thought. 
They try to read an input stream from a file. The stream is: 
"GOODGOODGOOFGOODGOODFOODGOODGOODGODGOODGOODGOODGOODBADIAMNIKOSGOODGOODGOOD"
The first read_and_crash is similar to the way stir is reading the files, when it find something that is not GOOD it return false and stop.
The second when finds something that is not GOOD backs half a record size and scans for the next 10*(max_size_record) to find a valid record. It is not optimised (not even close) but instead of criticise I preferred to provide a something more useful ;) and the actual modification is less than 8 lines.
The output from the first script: 
Started
Loop: 0
GOOD
Loop: 1
GOOD
Loop: 2
GOOF
NOT GOOD!!

And from the second: 
Started
Loop: 0
GOOD
Loop: 1
GOOD
Loop: 2
GOOF
NOT GOOD!!
FGOO
NOT GOOD!!
GOOD
Loop: 3
GOOD
Loop: 4
FOOD
NOT GOOD!!
DGOO
NOT GOOD!!
GOOD
Loop: 5
GOOD
Loop: 6
GODG
NOT GOOD!!
GOOD
Loop: 7
GOOD
Loop: 8
GOOD
Loop: 9
GOOD
Loop: 10
BADI
NOT GOOD!!
IAMN
NOT GOOD!!
AMNI
NOT GOOD!!
MNIK
NOT GOOD!!
NIKO
NOT GOOD!!
IKOS
NOT GOOD!!
KOSG
NOT GOOD!!
OSGO
NOT GOOD!!
SGOO
NOT GOOD!!
GOOD
Loop: 11
GOOD
Loop: 12
GOOD
Loop: 13

**Comment by danieldeidda** [comment]
This problem is related to the time tag contained inside the List Mode (LM) file and the use of time frame definition file. In particular, sometimes the mMR scanner save a LM file where the first event does not start at 0 s but at a time bigger than 0, **Te**. A very simple way to bypass this issue is to define a frame which instead of being **T** long will be **T+Te**. In this way, the events before **Te** will be zero and you read only those events inside the time window, **T**.
