### ISSUE TITLE
STIR python ProjData fill error

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#854]
I ran the following python code and get the error:

```
>>> import stir
>>> data = stir.ProjData_read_from_file("my_additive_sinogram.hs")

WARNING: Interfile warning: 'energy resolution' (0.124) is expected to be -1.000. Currently, the energy resolution and the reference energy, are used only in scatter correction.
>>> data.fill(1)

WARNING: write_data: error after writing to stream.


WARNING: ProjDataFromStream::set_segment: segment (-23) corrupted due to problems with writing or the scale factor 


ERROR: Error setting segment of projection data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Error setting segment of projection data
```

The data in `my_additive_sinogram.hs` appears file, I can use other tools to get valid stats etc... (read only). I tried this on sinogram file and got the same error but a `set_segment: segment (0)` (2D data). Is this an issue isolated to python?

**Comment by KrisThielemans** [comment]
You need to open read/write if you want to do this. The example has the code I believe

________________________________
From: robbietuk ***@***.***>
Sent: Friday, April 16, 2021 9:58:43 PM
To: UCL/STIR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [UCL/STIR] STIR python ProjData fill error (#854)


I ran the following python code to get the error

>>> import stir
>>> data = stir.ProjData_read_from_file("my_additive_sinogram.hs")

WARNING: Interfile warning: 'energy resolution' (0.124) is expected to be -1.000. Currently, the energy resolution and the reference energy, are used only in scatter correction.
>>> data.fill(1)

WARNING: write_data: error after writing to stream.


WARNING: ProjDataFromStream::set_segment: segment (-23) corrupted due to problems with writing or the scale factor


ERROR: Error setting segment of projection data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Error setting segment of projection data


The data in my_additive_sinogram.hs appears file, I can use other tools to get valid stats etc... (read only). I tried this on another data set and got the same error. Is this an issue isolated to python?

**Comment by robbietuk** [comment]
I can load into memory, this works.
```
>> import stir
>> data = stir.ProjData_read_from_file("my_additive_sinogram.hs")
>> data_in_memory = stir.ProjDataInMemory(data)
>> data_in_memory.get_segment_by_sinogram(0).find_max()
2906.31201171875
>> data_in_memory.fill(1)
>> data_in_memory.get_segment_by_sinogram(0).find_max()
1.0
>> data_in_memory.get_segment_by_sinogram(0).find_min()
1.0
```

**Comment by KrisThielemans** [comment]
yes of course.

the example code for read/write is
https://github.com/UCL/STIR/blob/974a7412bcd7cb843fcbb3e46c1b3a283c831a71/examples/python/projector_demo.py#L50-L51

**Comment by robbietuk** [comment]
Does that write the projdata to file for modifications? I assume this means that the there is constant I/O to the hard drive when modifications are made, whereas loading the data and keeping it in memory should be faster?

**Comment by KrisThielemans** [comment]
> Does that write the projdata to file for modifications? 

yes. (I thought that was obvious, but maybe not)

> I assume this means that the there is constant I/O to the hard drive when modifications are made, whereas loading the data and keeping it in memory should be faster?

yes, if you have enough memory

**Comment by robbietuk** [comment]
Got it. Thank you!
