### ISSUE TITLE
drop support for older C++ versions (switch to C++-11)

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#99]
we currently have work-arounds into place to be able to cope with older compilers. C++-11 has a lot of advantages however and is now well supported. Switching to C++-11 will allow us to write simpler code (and get rid of ugly work-arounds).

The plan is to enable C++-11 in the CMake file, and update the code gradually in new commits. There's no good reason to go back through all the existing code.

The code is currently C++-11 compatible already anyway (see e.g. #65, #63 and #90)

**Comment by dvolgyes** [comment]
Maybe it is time for another update: shall we drop openmp support for 3.0 or older?
OpenMP 3.1 is supported by gcc 4.7 and newer, and clang 3.7 and newer.
There are obscure openmp related 'ifdef's in the code, this could be removed from STIR 4.0 if we drop support for old OpenMP. (Not exactly true but almost:  c++11 requires a fresh enough compiler which also supports openmp 3.1.)

**Comment by KrisThielemans** [comment]
yeah, except that Visual Studio 2017 is still stuck on OpenMP 2.0. https://docs.microsoft.com/en-us/cpp/parallel/openmp/openmp-in-visual-cpp

**Comment by dvolgyes** [comment]
I wasn't aware of that.
Technically, you can call any compiler from VS, including clang/gcc/icc,
but you are right: MS' own compiler doesn't support anything beyond 2.0. I
was digging a bit, and I suspect this is intentional, and they try to push
their own C++Amp solution. It is a shame but that's life. So let' just keep
openmp in the current form.

**Comment by KrisThielemans** [comment]
reopening as the fix in #550 seems to be ignored
